//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 11:29:34 AM CEST 
//


package de.gematik.ws.fa.vsdm.vsd.v5;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Kostentraeger complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Kostentraeger">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Kostentraegerkennung">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Kostentraegerlaendercode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Name" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}name"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Kostentraeger", propOrder = {
    "kostentraegerkennung",
    "kostentraegerlaendercode",
    "name"
})
@XmlSeeAlso({
    de.gematik.ws.fa.vsdm.vsd.v5.UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz.Kostentraeger.class
})
public class Kostentraeger {

    @XmlElement(name = "Kostentraegerkennung", required = true)
    protected BigInteger kostentraegerkennung;
    @XmlElement(name = "Kostentraegerlaendercode", required = true)
    protected String kostentraegerlaendercode;
    @XmlElement(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the kostentraegerkennung property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKostentraegerkennung() {
        return kostentraegerkennung;
    }

    /**
     * Sets the value of the kostentraegerkennung property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKostentraegerkennung(BigInteger value) {
        this.kostentraegerkennung = value;
    }

    /**
     * Gets the value of the kostentraegerlaendercode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKostentraegerlaendercode() {
        return kostentraegerlaendercode;
    }

    /**
     * Sets the value of the kostentraegerlaendercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKostentraegerlaendercode(String value) {
        this.kostentraegerlaendercode = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
