//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 11:29:34 AM CEST 
//


package de.gematik.ws.fa.vsdm.vsd.v5;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.gematik.ws.fa.vsdm.vsd.v5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.gematik.ws.fa.vsdm.vsd.v5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UCPersoenlicheVersichertendatenXML }
     * 
     */
    public UCPersoenlicheVersichertendatenXML createUCPersoenlicheVersichertendatenXML() {
        return new UCPersoenlicheVersichertendatenXML();
    }

    /**
     * Create an instance of {@link UCAllgemeineVersicherungsdatenXML }
     * 
     */
    public UCAllgemeineVersicherungsdatenXML createUCAllgemeineVersicherungsdatenXML() {
        return new UCAllgemeineVersicherungsdatenXML();
    }

    /**
     * Create an instance of {@link UCGeschuetzteVersichertendatenXML }
     * 
     */
    public UCGeschuetzteVersichertendatenXML createUCGeschuetzteVersichertendatenXML() {
        return new UCGeschuetzteVersichertendatenXML();
    }

    /**
     * Create an instance of {@link UCAllgemeineVersicherungsdatenXML.Versicherter }
     * 
     */
    public UCAllgemeineVersicherungsdatenXML.Versicherter createUCAllgemeineVersicherungsdatenXMLVersicherter() {
        return new UCAllgemeineVersicherungsdatenXML.Versicherter();
    }

    /**
     * Create an instance of {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos }
     * 
     */
    public UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos createUCAllgemeineVersicherungsdatenXMLVersicherterZusatzinfos() {
        return new UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos();
    }

    /**
     * Create an instance of {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV }
     * 
     */
    public UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV createUCAllgemeineVersicherungsdatenXMLVersicherterZusatzinfosZusatzinfosGKV() {
        return new UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV();
    }

    /**
     * Create an instance of {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV }
     * 
     */
    public UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV createUCAllgemeineVersicherungsdatenXMLVersicherterZusatzinfosZusatzinfosGKVZusatzinfosAbrechnungGKV() {
        return new UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV();
    }

    /**
     * Create an instance of {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz }
     * 
     */
    public UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz createUCAllgemeineVersicherungsdatenXMLVersicherterVersicherungsschutz() {
        return new UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz();
    }

    /**
     * Create an instance of {@link UCPersoenlicheVersichertendatenXML.Versicherter }
     * 
     */
    public UCPersoenlicheVersichertendatenXML.Versicherter createUCPersoenlicheVersichertendatenXMLVersicherter() {
        return new UCPersoenlicheVersichertendatenXML.Versicherter();
    }

    /**
     * Create an instance of {@link UCPersoenlicheVersichertendatenXML.Versicherter.Person }
     * 
     */
    public UCPersoenlicheVersichertendatenXML.Versicherter.Person createUCPersoenlicheVersichertendatenXMLVersicherterPerson() {
        return new UCPersoenlicheVersichertendatenXML.Versicherter.Person();
    }

    /**
     * Create an instance of {@link UCGeschuetzteVersichertendatenXML.Zuzahlungsstatus }
     * 
     */
    public UCGeschuetzteVersichertendatenXML.Zuzahlungsstatus createUCGeschuetzteVersichertendatenXMLZuzahlungsstatus() {
        return new UCGeschuetzteVersichertendatenXML.Zuzahlungsstatus();
    }

    /**
     * Create an instance of {@link UCGeschuetzteVersichertendatenXML.Selektivvertraege }
     * 
     */
    public UCGeschuetzteVersichertendatenXML.Selektivvertraege createUCGeschuetzteVersichertendatenXMLSelektivvertraege() {
        return new UCGeschuetzteVersichertendatenXML.Selektivvertraege();
    }

    /**
     * Create an instance of {@link UCGeschuetzteVersichertendatenXML.RuhenderLeistungsanspruch }
     * 
     */
    public UCGeschuetzteVersichertendatenXML.RuhenderLeistungsanspruch createUCGeschuetzteVersichertendatenXMLRuhenderLeistungsanspruch() {
        return new UCGeschuetzteVersichertendatenXML.RuhenderLeistungsanspruch();
    }

    /**
     * Create an instance of {@link de.gematik.ws.fa.vsdm.vsd.v5.Kostentraeger }
     * 
     */
    public de.gematik.ws.fa.vsdm.vsd.v5.Kostentraeger createKostentraeger() {
        return new de.gematik.ws.fa.vsdm.vsd.v5.Kostentraeger();
    }

    /**
     * Create an instance of {@link LandType }
     * 
     */
    public LandType createLandType() {
        return new LandType();
    }

    /**
     * Create an instance of {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV.Kostenerstattung }
     * 
     */
    public UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV.Kostenerstattung createUCAllgemeineVersicherungsdatenXMLVersicherterZusatzinfosZusatzinfosGKVZusatzinfosAbrechnungGKVKostenerstattung() {
        return new UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV.Kostenerstattung();
    }

    /**
     * Create an instance of {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz.Kostentraeger }
     * 
     */
    public UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz.Kostentraeger createUCAllgemeineVersicherungsdatenXMLVersicherterVersicherungsschutzKostentraeger() {
        return new UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz.Kostentraeger();
    }

    /**
     * Create an instance of {@link UCPersoenlicheVersichertendatenXML.Versicherter.Person.PostfachAdresse }
     * 
     */
    public UCPersoenlicheVersichertendatenXML.Versicherter.Person.PostfachAdresse createUCPersoenlicheVersichertendatenXMLVersicherterPersonPostfachAdresse() {
        return new UCPersoenlicheVersichertendatenXML.Versicherter.Person.PostfachAdresse();
    }

    /**
     * Create an instance of {@link UCPersoenlicheVersichertendatenXML.Versicherter.Person.StrassenAdresse }
     * 
     */
    public UCPersoenlicheVersichertendatenXML.Versicherter.Person.StrassenAdresse createUCPersoenlicheVersichertendatenXMLVersicherterPersonStrassenAdresse() {
        return new UCPersoenlicheVersichertendatenXML.Versicherter.Person.StrassenAdresse();
    }

}
