//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 11:29:34 AM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ws.gematik.de/fa/vsdm/vsd/v5.2", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.gematik.ws.fa.vsdm.vsd.v5;
