//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 11:29:34 AM CEST 
//


package de.gematik.ws.fa.vsdm.vsd.v5;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import de.gematik.ws.fa.vsdm.vsd.v5.runtime.ZeroOneBooleanAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Versicherter">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Versicherungsschutz">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Beginn" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date"/>
 *                             &lt;element name="Ende" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date" minOccurs="0"/>
 *                             &lt;element name="Kostentraeger">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;extension base="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}Kostentraeger">
 *                                     &lt;sequence>
 *                                       &lt;element name="AbrechnenderKostentraeger" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}Kostentraeger" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/extension>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Zusatzinfos">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ZusatzinfosGKV">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Versichertenart" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codedString"/>
 *                                       &lt;element name="Zusatzinfos_Abrechnung_GKV">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Kostenerstattung" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="AerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
 *                                                           &lt;element name="ZahnaerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
 *                                                           &lt;element name="StationaererBereich" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
 *                                                           &lt;element name="VeranlassteLeistungen" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="WOP" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}numberWithLeadingZero"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="CDM_VERSION" use="required" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}CDMVersion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "versicherter"
})
@XmlRootElement(name = "UC_AllgemeineVersicherungsdatenXML")
public class UCAllgemeineVersicherungsdatenXML {

    @XmlElement(name = "Versicherter", required = true)
    protected UCAllgemeineVersicherungsdatenXML.Versicherter versicherter;
    @XmlAttribute(name = "CDM_VERSION", required = true)
    protected String cdmversion;

    /**
     * Gets the value of the versicherter property.
     * 
     * @return
     *     possible object is
     *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter }
     *     
     */
    public UCAllgemeineVersicherungsdatenXML.Versicherter getVersicherter() {
        return versicherter;
    }

    /**
     * Sets the value of the versicherter property.
     * 
     * @param value
     *     allowed object is
     *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter }
     *     
     */
    public void setVersicherter(UCAllgemeineVersicherungsdatenXML.Versicherter value) {
        this.versicherter = value;
    }

    /**
     * Gets the value of the cdmversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDMVERSION() {
        return cdmversion;
    }

    /**
     * Sets the value of the cdmversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDMVERSION(String value) {
        this.cdmversion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Versicherungsschutz">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Beginn" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date"/>
     *                   &lt;element name="Ende" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date" minOccurs="0"/>
     *                   &lt;element name="Kostentraeger">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;extension base="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}Kostentraeger">
     *                           &lt;sequence>
     *                             &lt;element name="AbrechnenderKostentraeger" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}Kostentraeger" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/extension>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Zusatzinfos">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ZusatzinfosGKV">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Versichertenart" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codedString"/>
     *                             &lt;element name="Zusatzinfos_Abrechnung_GKV">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Kostenerstattung" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="AerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
     *                                                 &lt;element name="ZahnaerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
     *                                                 &lt;element name="StationaererBereich" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
     *                                                 &lt;element name="VeranlassteLeistungen" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="WOP" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}numberWithLeadingZero"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "versicherungsschutz",
        "zusatzinfos"
    })
    public static class Versicherter {

        @XmlElement(name = "Versicherungsschutz", required = true)
        protected UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz versicherungsschutz;
        @XmlElement(name = "Zusatzinfos", required = true)
        protected UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos zusatzinfos;

        /**
         * Gets the value of the versicherungsschutz property.
         * 
         * @return
         *     possible object is
         *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz }
         *     
         */
        public UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz getVersicherungsschutz() {
            return versicherungsschutz;
        }

        /**
         * Sets the value of the versicherungsschutz property.
         * 
         * @param value
         *     allowed object is
         *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz }
         *     
         */
        public void setVersicherungsschutz(UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz value) {
            this.versicherungsschutz = value;
        }

        /**
         * Gets the value of the zusatzinfos property.
         * 
         * @return
         *     possible object is
         *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos }
         *     
         */
        public UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos getZusatzinfos() {
            return zusatzinfos;
        }

        /**
         * Sets the value of the zusatzinfos property.
         * 
         * @param value
         *     allowed object is
         *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos }
         *     
         */
        public void setZusatzinfos(UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos value) {
            this.zusatzinfos = value;
        }


        /**
         * Es handelt sich um eine Pflichtangabe.
         * 
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Beginn" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date"/>
         *         &lt;element name="Ende" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date" minOccurs="0"/>
         *         &lt;element name="Kostentraeger">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;extension base="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}Kostentraeger">
         *                 &lt;sequence>
         *                   &lt;element name="AbrechnenderKostentraeger" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}Kostentraeger" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/extension>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "beginn",
            "ende",
            "kostentraeger"
        })
        public static class Versicherungsschutz {

            @XmlElement(name = "Beginn", required = true)
            protected String beginn;
            @XmlElement(name = "Ende")
            protected String ende;
            @XmlElement(name = "Kostentraeger", required = true)
            protected UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz.Kostentraeger kostentraeger;

            /**
             * Gets the value of the beginn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBeginn() {
                return beginn;
            }

            /**
             * Sets the value of the beginn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBeginn(String value) {
                this.beginn = value;
            }

            /**
             * Gets the value of the ende property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEnde() {
                return ende;
            }

            /**
             * Sets the value of the ende property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEnde(String value) {
                this.ende = value;
            }

            /**
             * Gets the value of the kostentraeger property.
             * 
             * @return
             *     possible object is
             *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz.Kostentraeger }
             *     
             */
            public UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz.Kostentraeger getKostentraeger() {
                return kostentraeger;
            }

            /**
             * Sets the value of the kostentraeger property.
             * 
             * @param value
             *     allowed object is
             *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz.Kostentraeger }
             *     
             */
            public void setKostentraeger(UCAllgemeineVersicherungsdatenXML.Versicherter.Versicherungsschutz.Kostentraeger value) {
                this.kostentraeger = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;extension base="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}Kostentraeger">
             *       &lt;sequence>
             *         &lt;element name="AbrechnenderKostentraeger" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}Kostentraeger" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/extension>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "abrechnenderKostentraeger"
            })
            public static class Kostentraeger
                extends de.gematik.ws.fa.vsdm.vsd.v5.Kostentraeger
            {

                @XmlElement(name = "AbrechnenderKostentraeger")
                protected de.gematik.ws.fa.vsdm.vsd.v5.Kostentraeger abrechnenderKostentraeger;

                /**
                 * Gets the value of the abrechnenderKostentraeger property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link de.gematik.ws.fa.vsdm.vsd.v5.Kostentraeger }
                 *     
                 */
                public de.gematik.ws.fa.vsdm.vsd.v5.Kostentraeger getAbrechnenderKostentraeger() {
                    return abrechnenderKostentraeger;
                }

                /**
                 * Sets the value of the abrechnenderKostentraeger property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link de.gematik.ws.fa.vsdm.vsd.v5.Kostentraeger }
                 *     
                 */
                public void setAbrechnenderKostentraeger(de.gematik.ws.fa.vsdm.vsd.v5.Kostentraeger value) {
                    this.abrechnenderKostentraeger = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ZusatzinfosGKV">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Versichertenart" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codedString"/>
         *                   &lt;element name="Zusatzinfos_Abrechnung_GKV">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Kostenerstattung" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="AerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
         *                                       &lt;element name="ZahnaerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
         *                                       &lt;element name="StationaererBereich" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
         *                                       &lt;element name="VeranlassteLeistungen" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="WOP" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}numberWithLeadingZero"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "zusatzinfosGKV"
        })
        public static class Zusatzinfos {

            @XmlElement(name = "ZusatzinfosGKV", required = true)
            protected UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV zusatzinfosGKV;

            /**
             * Gets the value of the zusatzinfosGKV property.
             * 
             * @return
             *     possible object is
             *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV }
             *     
             */
            public UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV getZusatzinfosGKV() {
                return zusatzinfosGKV;
            }

            /**
             * Sets the value of the zusatzinfosGKV property.
             * 
             * @param value
             *     allowed object is
             *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV }
             *     
             */
            public void setZusatzinfosGKV(UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV value) {
                this.zusatzinfosGKV = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Versichertenart" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codedString"/>
             *         &lt;element name="Zusatzinfos_Abrechnung_GKV">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Kostenerstattung" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="AerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
             *                             &lt;element name="ZahnaerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
             *                             &lt;element name="StationaererBereich" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
             *                             &lt;element name="VeranlassteLeistungen" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="WOP" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}numberWithLeadingZero"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "versichertenart",
                "zusatzinfosAbrechnungGKV"
            })
            public static class ZusatzinfosGKV {

                @XmlElement(name = "Versichertenart", required = true)
                protected String versichertenart;
                @XmlElement(name = "Zusatzinfos_Abrechnung_GKV", required = true)
                protected UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV zusatzinfosAbrechnungGKV;

                /**
                 * Gets the value of the versichertenart property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVersichertenart() {
                    return versichertenart;
                }

                /**
                 * Sets the value of the versichertenart property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVersichertenart(String value) {
                    this.versichertenart = value;
                }

                /**
                 * Gets the value of the zusatzinfosAbrechnungGKV property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV }
                 *     
                 */
                public UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV getZusatzinfosAbrechnungGKV() {
                    return zusatzinfosAbrechnungGKV;
                }

                /**
                 * Sets the value of the zusatzinfosAbrechnungGKV property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV }
                 *     
                 */
                public void setZusatzinfosAbrechnungGKV(UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV value) {
                    this.zusatzinfosAbrechnungGKV = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Kostenerstattung" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="AerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
                 *                   &lt;element name="ZahnaerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
                 *                   &lt;element name="StationaererBereich" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
                 *                   &lt;element name="VeranlassteLeistungen" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="WOP" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}numberWithLeadingZero"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "kostenerstattung",
                    "wop"
                })
                public static class ZusatzinfosAbrechnungGKV {

                    @XmlElement(name = "Kostenerstattung")
                    protected UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV.Kostenerstattung kostenerstattung;
                    @XmlElement(name = "WOP", required = true)
                    protected String wop;

                    /**
                     * Gets the value of the kostenerstattung property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV.Kostenerstattung }
                     *     
                     */
                    public UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV.Kostenerstattung getKostenerstattung() {
                        return kostenerstattung;
                    }

                    /**
                     * Sets the value of the kostenerstattung property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV.Kostenerstattung }
                     *     
                     */
                    public void setKostenerstattung(UCAllgemeineVersicherungsdatenXML.Versicherter.Zusatzinfos.ZusatzinfosGKV.ZusatzinfosAbrechnungGKV.Kostenerstattung value) {
                        this.kostenerstattung = value;
                    }

                    /**
                     * Gets the value of the wop property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getWOP() {
                        return wop;
                    }

                    /**
                     * Sets the value of the wop property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setWOP(String value) {
                        this.wop = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="AerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
                     *         &lt;element name="ZahnaerztlicheVersorgung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
                     *         &lt;element name="StationaererBereich" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
                     *         &lt;element name="VeranlassteLeistungen" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}boolean"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "aerztlicheVersorgung",
                        "zahnaerztlicheVersorgung",
                        "stationaererBereich",
                        "veranlassteLeistungen"
                    })
                    public static class Kostenerstattung {

                        @XmlElement(name = "AerztlicheVersorgung", required = true, type = String.class)
                        @XmlJavaTypeAdapter(ZeroOneBooleanAdapter.class)
                        @XmlSchemaType(name = "boolean")
                        protected Boolean aerztlicheVersorgung;
                        @XmlElement(name = "ZahnaerztlicheVersorgung", required = true, type = String.class)
                        @XmlJavaTypeAdapter(ZeroOneBooleanAdapter.class)
                        @XmlSchemaType(name = "boolean")
                        protected Boolean zahnaerztlicheVersorgung;
                        @XmlElement(name = "StationaererBereich", required = true, type = String.class)
                        @XmlJavaTypeAdapter(ZeroOneBooleanAdapter.class)
                        @XmlSchemaType(name = "boolean")
                        protected Boolean stationaererBereich;
                        @XmlElement(name = "VeranlassteLeistungen", required = true, type = String.class)
                        @XmlJavaTypeAdapter(ZeroOneBooleanAdapter.class)
                        @XmlSchemaType(name = "boolean")
                        protected Boolean veranlassteLeistungen;

                        /**
                         * Gets the value of the aerztlicheVersorgung property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public Boolean isAerztlicheVersorgung() {
                            return aerztlicheVersorgung;
                        }

                        /**
                         * Sets the value of the aerztlicheVersorgung property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAerztlicheVersorgung(Boolean value) {
                            this.aerztlicheVersorgung = value;
                        }

                        /**
                         * Gets the value of the zahnaerztlicheVersorgung property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public Boolean isZahnaerztlicheVersorgung() {
                            return zahnaerztlicheVersorgung;
                        }

                        /**
                         * Sets the value of the zahnaerztlicheVersorgung property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setZahnaerztlicheVersorgung(Boolean value) {
                            this.zahnaerztlicheVersorgung = value;
                        }

                        /**
                         * Gets the value of the stationaererBereich property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public Boolean isStationaererBereich() {
                            return stationaererBereich;
                        }

                        /**
                         * Sets the value of the stationaererBereich property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setStationaererBereich(Boolean value) {
                            this.stationaererBereich = value;
                        }

                        /**
                         * Gets the value of the veranlassteLeistungen property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public Boolean isVeranlassteLeistungen() {
                            return veranlassteLeistungen;
                        }

                        /**
                         * Sets the value of the veranlassteLeistungen property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setVeranlassteLeistungen(Boolean value) {
                            this.veranlassteLeistungen = value;
                        }

                    }

                }

            }

        }

    }

}
