//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 11:29:34 AM CEST 
//


package de.gematik.ws.fa.vsdm.vsd.v5;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Zuzahlungsstatus">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Status" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}booleanInteger"/>
 *                   &lt;element name="Gueltig_bis" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BesonderePersonengruppe" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codeDigits" minOccurs="0"/>
 *         &lt;element name="DMP_Kennzeichnung" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codeDigits" minOccurs="0"/>
 *         &lt;element name="Selektivvertraege">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Aerztlich" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codeDigit"/>
 *                   &lt;element name="Zahnaerztlich" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codeDigit"/>
 *                   &lt;element name="Art" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0-1]{4}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RuhenderLeistungsanspruch" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Beginn" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date"/>
 *                   &lt;element name="Ende" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date" minOccurs="0"/>
 *                   &lt;element name="ArtDesRuhens" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codeDigit"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="CDM_VERSION" use="required" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}CDMVersion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zuzahlungsstatus",
    "besonderePersonengruppe",
    "dmpKennzeichnung",
    "selektivvertraege",
    "ruhenderLeistungsanspruch"
})
@XmlRootElement(name = "UC_GeschuetzteVersichertendatenXML")
public class UCGeschuetzteVersichertendatenXML {

    @XmlElement(name = "Zuzahlungsstatus", required = true)
    protected UCGeschuetzteVersichertendatenXML.Zuzahlungsstatus zuzahlungsstatus;
    @XmlElement(name = "BesonderePersonengruppe")
    protected BigInteger besonderePersonengruppe;
    @XmlElement(name = "DMP_Kennzeichnung")
    protected BigInteger dmpKennzeichnung;
    @XmlElement(name = "Selektivvertraege", required = true)
    protected UCGeschuetzteVersichertendatenXML.Selektivvertraege selektivvertraege;
    @XmlElement(name = "RuhenderLeistungsanspruch")
    protected UCGeschuetzteVersichertendatenXML.RuhenderLeistungsanspruch ruhenderLeistungsanspruch;
    @XmlAttribute(name = "CDM_VERSION", required = true)
    protected String cdmversion;

    /**
     * Gets the value of the zuzahlungsstatus property.
     * 
     * @return
     *     possible object is
     *     {@link UCGeschuetzteVersichertendatenXML.Zuzahlungsstatus }
     *     
     */
    public UCGeschuetzteVersichertendatenXML.Zuzahlungsstatus getZuzahlungsstatus() {
        return zuzahlungsstatus;
    }

    /**
     * Sets the value of the zuzahlungsstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link UCGeschuetzteVersichertendatenXML.Zuzahlungsstatus }
     *     
     */
    public void setZuzahlungsstatus(UCGeschuetzteVersichertendatenXML.Zuzahlungsstatus value) {
        this.zuzahlungsstatus = value;
    }

    /**
     * Gets the value of the besonderePersonengruppe property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBesonderePersonengruppe() {
        return besonderePersonengruppe;
    }

    /**
     * Sets the value of the besonderePersonengruppe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBesonderePersonengruppe(BigInteger value) {
        this.besonderePersonengruppe = value;
    }

    /**
     * Gets the value of the dmpKennzeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDMPKennzeichnung() {
        return dmpKennzeichnung;
    }

    /**
     * Sets the value of the dmpKennzeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDMPKennzeichnung(BigInteger value) {
        this.dmpKennzeichnung = value;
    }

    /**
     * Gets the value of the selektivvertraege property.
     * 
     * @return
     *     possible object is
     *     {@link UCGeschuetzteVersichertendatenXML.Selektivvertraege }
     *     
     */
    public UCGeschuetzteVersichertendatenXML.Selektivvertraege getSelektivvertraege() {
        return selektivvertraege;
    }

    /**
     * Sets the value of the selektivvertraege property.
     * 
     * @param value
     *     allowed object is
     *     {@link UCGeschuetzteVersichertendatenXML.Selektivvertraege }
     *     
     */
    public void setSelektivvertraege(UCGeschuetzteVersichertendatenXML.Selektivvertraege value) {
        this.selektivvertraege = value;
    }

    /**
     * Gets the value of the ruhenderLeistungsanspruch property.
     * 
     * @return
     *     possible object is
     *     {@link UCGeschuetzteVersichertendatenXML.RuhenderLeistungsanspruch }
     *     
     */
    public UCGeschuetzteVersichertendatenXML.RuhenderLeistungsanspruch getRuhenderLeistungsanspruch() {
        return ruhenderLeistungsanspruch;
    }

    /**
     * Sets the value of the ruhenderLeistungsanspruch property.
     * 
     * @param value
     *     allowed object is
     *     {@link UCGeschuetzteVersichertendatenXML.RuhenderLeistungsanspruch }
     *     
     */
    public void setRuhenderLeistungsanspruch(UCGeschuetzteVersichertendatenXML.RuhenderLeistungsanspruch value) {
        this.ruhenderLeistungsanspruch = value;
    }

    /**
     * Gets the value of the cdmversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDMVERSION() {
        return cdmversion;
    }

    /**
     * Sets the value of the cdmversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDMVERSION(String value) {
        this.cdmversion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Beginn" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date"/>
     *         &lt;element name="Ende" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date" minOccurs="0"/>
     *         &lt;element name="ArtDesRuhens" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codeDigit"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "beginn",
        "ende",
        "artDesRuhens"
    })
    public static class RuhenderLeistungsanspruch {

        @XmlElement(name = "Beginn", required = true)
        protected String beginn;
        @XmlElement(name = "Ende")
        protected String ende;
        @XmlElement(name = "ArtDesRuhens", required = true)
        protected BigInteger artDesRuhens;

        /**
         * Gets the value of the beginn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeginn() {
            return beginn;
        }

        /**
         * Sets the value of the beginn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeginn(String value) {
            this.beginn = value;
        }

        /**
         * Gets the value of the ende property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnde() {
            return ende;
        }

        /**
         * Sets the value of the ende property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnde(String value) {
            this.ende = value;
        }

        /**
         * Gets the value of the artDesRuhens property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getArtDesRuhens() {
            return artDesRuhens;
        }

        /**
         * Sets the value of the artDesRuhens property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setArtDesRuhens(BigInteger value) {
            this.artDesRuhens = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Aerztlich" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codeDigit"/>
     *         &lt;element name="Zahnaerztlich" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}codeDigit"/>
     *         &lt;element name="Art" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-1]{4}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aerztlich",
        "zahnaerztlich",
        "art"
    })
    public static class Selektivvertraege {

        @XmlElement(name = "Aerztlich", required = true)
        protected BigInteger aerztlich;
        @XmlElement(name = "Zahnaerztlich", required = true)
        protected BigInteger zahnaerztlich;
        @XmlElement(name = "Art")
        protected String art;

        /**
         * Gets the value of the aerztlich property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAerztlich() {
            return aerztlich;
        }

        /**
         * Sets the value of the aerztlich property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAerztlich(BigInteger value) {
            this.aerztlich = value;
        }

        /**
         * Gets the value of the zahnaerztlich property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getZahnaerztlich() {
            return zahnaerztlich;
        }

        /**
         * Sets the value of the zahnaerztlich property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setZahnaerztlich(BigInteger value) {
            this.zahnaerztlich = value;
        }

        /**
         * Gets the value of the art property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArt() {
            return art;
        }

        /**
         * Sets the value of the art property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArt(String value) {
            this.art = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Status" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}booleanInteger"/>
     *         &lt;element name="Gueltig_bis" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "gueltigBis"
    })
    public static class Zuzahlungsstatus {

        @XmlElement(name = "Status", required = true)
        protected BigInteger status;
        @XmlElement(name = "Gueltig_bis")
        protected String gueltigBis;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setStatus(BigInteger value) {
            this.status = value;
        }

        /**
         * Gets the value of the gueltigBis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGueltigBis() {
            return gueltigBis;
        }

        /**
         * Sets the value of the gueltigBis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGueltigBis(String value) {
            this.gueltigBis = value;
        }

    }

}
