//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.22 at 11:29:34 AM CEST 
//


package de.gematik.ws.fa.vsdm.vsd.v5;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Versicherter">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Versicherten_ID" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}insurantId"/>
 *                   &lt;element name="Person">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Geburtsdatum" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date"/>
 *                             &lt;element name="Vorname">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}name">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Nachname">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}name">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Geschlecht" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}gender"/>
 *                             &lt;element name="Vorsatzwort" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}nameExtension" minOccurs="0"/>
 *                             &lt;element name="Namenszusatz" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}nameExtension" minOccurs="0"/>
 *                             &lt;element name="Titel" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}nameExtension" minOccurs="0"/>
 *                             &lt;element name="PostfachAdresse" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Postleitzahl" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="10"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Ort">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="40"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Postfach">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="8"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Land" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}LandType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="StrassenAdresse" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Postleitzahl" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="10"/>
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Ort">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="40"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Land" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}LandType"/>
 *                                       &lt;element name="Strasse" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="46"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Hausnummer" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="9"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Anschriftenzusatz" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="40"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="CDM_VERSION" use="required" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}CDMVersion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "versicherter"
})
@XmlRootElement(name = "UC_PersoenlicheVersichertendatenXML")
public class UCPersoenlicheVersichertendatenXML {

    @XmlElement(name = "Versicherter", required = true)
    protected UCPersoenlicheVersichertendatenXML.Versicherter versicherter;
    @XmlAttribute(name = "CDM_VERSION", required = true)
    protected String cdmversion;

    /**
     * Gets the value of the versicherter property.
     * 
     * @return
     *     possible object is
     *     {@link UCPersoenlicheVersichertendatenXML.Versicherter }
     *     
     */
    public UCPersoenlicheVersichertendatenXML.Versicherter getVersicherter() {
        return versicherter;
    }

    /**
     * Sets the value of the versicherter property.
     * 
     * @param value
     *     allowed object is
     *     {@link UCPersoenlicheVersichertendatenXML.Versicherter }
     *     
     */
    public void setVersicherter(UCPersoenlicheVersichertendatenXML.Versicherter value) {
        this.versicherter = value;
    }

    /**
     * Gets the value of the cdmversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDMVERSION() {
        return cdmversion;
    }

    /**
     * Sets the value of the cdmversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDMVERSION(String value) {
        this.cdmversion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Versicherten_ID" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}insurantId"/>
     *         &lt;element name="Person">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Geburtsdatum" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date"/>
     *                   &lt;element name="Vorname">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}name">
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Nachname">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}name">
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Geschlecht" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}gender"/>
     *                   &lt;element name="Vorsatzwort" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}nameExtension" minOccurs="0"/>
     *                   &lt;element name="Namenszusatz" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}nameExtension" minOccurs="0"/>
     *                   &lt;element name="Titel" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}nameExtension" minOccurs="0"/>
     *                   &lt;element name="PostfachAdresse" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Postleitzahl" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="10"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Ort">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="40"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Postfach">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="8"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Land" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}LandType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="StrassenAdresse" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Postleitzahl" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="10"/>
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Ort">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="40"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Land" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}LandType"/>
     *                             &lt;element name="Strasse" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="46"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Hausnummer" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="9"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Anschriftenzusatz" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="40"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "versichertenID",
        "person"
    })
    public static class Versicherter {

        @XmlElement(name = "Versicherten_ID", required = true)
        protected String versichertenID;
        @XmlElement(name = "Person", required = true)
        protected UCPersoenlicheVersichertendatenXML.Versicherter.Person person;

        /**
         * Gets the value of the versichertenID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersichertenID() {
            return versichertenID;
        }

        /**
         * Sets the value of the versichertenID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersichertenID(String value) {
            this.versichertenID = value;
        }

        /**
         * Gets the value of the person property.
         * 
         * @return
         *     possible object is
         *     {@link UCPersoenlicheVersichertendatenXML.Versicherter.Person }
         *     
         */
        public UCPersoenlicheVersichertendatenXML.Versicherter.Person getPerson() {
            return person;
        }

        /**
         * Sets the value of the person property.
         * 
         * @param value
         *     allowed object is
         *     {@link UCPersoenlicheVersichertendatenXML.Versicherter.Person }
         *     
         */
        public void setPerson(UCPersoenlicheVersichertendatenXML.Versicherter.Person value) {
            this.person = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Geburtsdatum" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}ISO8601Date"/>
         *         &lt;element name="Vorname">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}name">
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Nachname">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}name">
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Geschlecht" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}gender"/>
         *         &lt;element name="Vorsatzwort" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}nameExtension" minOccurs="0"/>
         *         &lt;element name="Namenszusatz" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}nameExtension" minOccurs="0"/>
         *         &lt;element name="Titel" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}nameExtension" minOccurs="0"/>
         *         &lt;element name="PostfachAdresse" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Postleitzahl" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="10"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Ort">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="40"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Postfach">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="8"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Land" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}LandType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="StrassenAdresse" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Postleitzahl" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="10"/>
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Ort">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="40"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Land" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}LandType"/>
         *                   &lt;element name="Strasse" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="46"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Hausnummer" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="9"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Anschriftenzusatz" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="40"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "geburtsdatum",
            "vorname",
            "nachname",
            "geschlecht",
            "vorsatzwort",
            "namenszusatz",
            "titel",
            "postfachAdresse",
            "strassenAdresse"
        })
        public static class Person {

            @XmlElement(name = "Geburtsdatum", required = true)
            protected String geburtsdatum;
            @XmlElement(name = "Vorname", required = true)
            protected String vorname;
            @XmlElement(name = "Nachname", required = true)
            protected String nachname;
            @XmlElement(name = "Geschlecht", required = true)
            protected String geschlecht;
            @XmlElement(name = "Vorsatzwort")
            protected String vorsatzwort;
            @XmlElement(name = "Namenszusatz")
            protected String namenszusatz;
            @XmlElement(name = "Titel")
            protected String titel;
            @XmlElement(name = "PostfachAdresse")
            protected UCPersoenlicheVersichertendatenXML.Versicherter.Person.PostfachAdresse postfachAdresse;
            @XmlElement(name = "StrassenAdresse")
            protected UCPersoenlicheVersichertendatenXML.Versicherter.Person.StrassenAdresse strassenAdresse;

            /**
             * Gets the value of the geburtsdatum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGeburtsdatum() {
                return geburtsdatum;
            }

            /**
             * Sets the value of the geburtsdatum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGeburtsdatum(String value) {
                this.geburtsdatum = value;
            }

            /**
             * Gets the value of the vorname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVorname() {
                return vorname;
            }

            /**
             * Sets the value of the vorname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVorname(String value) {
                this.vorname = value;
            }

            /**
             * Gets the value of the nachname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNachname() {
                return nachname;
            }

            /**
             * Sets the value of the nachname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNachname(String value) {
                this.nachname = value;
            }

            /**
             * Gets the value of the geschlecht property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGeschlecht() {
                return geschlecht;
            }

            /**
             * Sets the value of the geschlecht property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGeschlecht(String value) {
                this.geschlecht = value;
            }

            /**
             * Gets the value of the vorsatzwort property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVorsatzwort() {
                return vorsatzwort;
            }

            /**
             * Sets the value of the vorsatzwort property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVorsatzwort(String value) {
                this.vorsatzwort = value;
            }

            /**
             * Gets the value of the namenszusatz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNamenszusatz() {
                return namenszusatz;
            }

            /**
             * Sets the value of the namenszusatz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNamenszusatz(String value) {
                this.namenszusatz = value;
            }

            /**
             * Gets the value of the titel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitel() {
                return titel;
            }

            /**
             * Sets the value of the titel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitel(String value) {
                this.titel = value;
            }

            /**
             * Gets the value of the postfachAdresse property.
             * 
             * @return
             *     possible object is
             *     {@link UCPersoenlicheVersichertendatenXML.Versicherter.Person.PostfachAdresse }
             *     
             */
            public UCPersoenlicheVersichertendatenXML.Versicherter.Person.PostfachAdresse getPostfachAdresse() {
                return postfachAdresse;
            }

            /**
             * Sets the value of the postfachAdresse property.
             * 
             * @param value
             *     allowed object is
             *     {@link UCPersoenlicheVersichertendatenXML.Versicherter.Person.PostfachAdresse }
             *     
             */
            public void setPostfachAdresse(UCPersoenlicheVersichertendatenXML.Versicherter.Person.PostfachAdresse value) {
                this.postfachAdresse = value;
            }

            /**
             * Gets the value of the strassenAdresse property.
             * 
             * @return
             *     possible object is
             *     {@link UCPersoenlicheVersichertendatenXML.Versicherter.Person.StrassenAdresse }
             *     
             */
            public UCPersoenlicheVersichertendatenXML.Versicherter.Person.StrassenAdresse getStrassenAdresse() {
                return strassenAdresse;
            }

            /**
             * Sets the value of the strassenAdresse property.
             * 
             * @param value
             *     allowed object is
             *     {@link UCPersoenlicheVersichertendatenXML.Versicherter.Person.StrassenAdresse }
             *     
             */
            public void setStrassenAdresse(UCPersoenlicheVersichertendatenXML.Versicherter.Person.StrassenAdresse value) {
                this.strassenAdresse = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Postleitzahl" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="10"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Ort">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="40"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Postfach">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="8"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Land" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}LandType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "postleitzahl",
                "ort",
                "postfach",
                "land"
            })
            public static class PostfachAdresse {

                @XmlElement(name = "Postleitzahl")
                protected String postleitzahl;
                @XmlElement(name = "Ort", required = true)
                protected String ort;
                @XmlElement(name = "Postfach", required = true)
                protected String postfach;
                @XmlElement(name = "Land", required = true)
                protected LandType land;

                /**
                 * Gets the value of the postleitzahl property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPostleitzahl() {
                    return postleitzahl;
                }

                /**
                 * Sets the value of the postleitzahl property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPostleitzahl(String value) {
                    this.postleitzahl = value;
                }

                /**
                 * Gets the value of the ort property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOrt() {
                    return ort;
                }

                /**
                 * Sets the value of the ort property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOrt(String value) {
                    this.ort = value;
                }

                /**
                 * Gets the value of the postfach property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPostfach() {
                    return postfach;
                }

                /**
                 * Sets the value of the postfach property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPostfach(String value) {
                    this.postfach = value;
                }

                /**
                 * Gets the value of the land property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link LandType }
                 *     
                 */
                public LandType getLand() {
                    return land;
                }

                /**
                 * Sets the value of the land property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link LandType }
                 *     
                 */
                public void setLand(LandType value) {
                    this.land = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Postleitzahl" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="10"/>
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Ort">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="40"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Land" type="{http://ws.gematik.de/fa/vsdm/vsd/v5.2}LandType"/>
             *         &lt;element name="Strasse" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="46"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Hausnummer" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="9"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Anschriftenzusatz" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="40"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "postleitzahl",
                "ort",
                "land",
                "strasse",
                "hausnummer",
                "anschriftenzusatz"
            })
            public static class StrassenAdresse {

                @XmlElement(name = "Postleitzahl")
                protected String postleitzahl;
                @XmlElement(name = "Ort", required = true)
                protected String ort;
                @XmlElement(name = "Land", required = true)
                protected LandType land;
                @XmlElement(name = "Strasse")
                protected String strasse;
                @XmlElement(name = "Hausnummer")
                protected String hausnummer;
                @XmlElement(name = "Anschriftenzusatz")
                protected String anschriftenzusatz;

                /**
                 * Gets the value of the postleitzahl property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPostleitzahl() {
                    return postleitzahl;
                }

                /**
                 * Sets the value of the postleitzahl property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPostleitzahl(String value) {
                    this.postleitzahl = value;
                }

                /**
                 * Gets the value of the ort property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOrt() {
                    return ort;
                }

                /**
                 * Sets the value of the ort property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOrt(String value) {
                    this.ort = value;
                }

                /**
                 * Gets the value of the land property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link LandType }
                 *     
                 */
                public LandType getLand() {
                    return land;
                }

                /**
                 * Sets the value of the land property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link LandType }
                 *     
                 */
                public void setLand(LandType value) {
                    this.land = value;
                }

                /**
                 * Gets the value of the strasse property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStrasse() {
                    return strasse;
                }

                /**
                 * Sets the value of the strasse property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStrasse(String value) {
                    this.strasse = value;
                }

                /**
                 * Gets the value of the hausnummer property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHausnummer() {
                    return hausnummer;
                }

                /**
                 * Sets the value of the hausnummer property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHausnummer(String value) {
                    this.hausnummer = value;
                }

                /**
                 * Gets the value of the anschriftenzusatz property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAnschriftenzusatz() {
                    return anschriftenzusatz;
                }

                /**
                 * Sets the value of the anschriftenzusatz property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAnschriftenzusatz(String value) {
                    this.anschriftenzusatz = value;
                }

            }

        }

    }

}
